package net.bigpoint.cityrama.model.quest
{
   public class VirtualTaskNotificationInterest
   {
      
      public static const ARCHITECTUAL_BOOK_OPENED:String = "ARCHITECTUAL_BOOK_OPENED";
      
      public static const ARCHITECTUAL_BOOK_CLOSED:String = " ARCHITECTUAL_BOOK_CLOSED";
      
      public static const ARCHITECTUAL_BOOK_PLACE_CLICKED:String = "ARCHITECTUAL_BOOK_PLACE_CLICKED";
      
      public static const RESIDENTIAL_CATEGORY_PLACE_SELECTED:String = "RESIDENTIAL_CATEGORY_PLACE_SELECTED";
      
      public static const PRODUCTION_CATEGORY_PLACE_SELECTED:String = "PRODUCTION_CATEGORY_PLACE_SELECTED";
      
      public static const GROUND_CATEGORY_PLACE_SELECTED:String = "GROUND_CATEGORY_PLACE_SELECTED";
      
      public static const ARCHITECTUAL_BOOK_RESIDENTIAL_SELECTED:String = "ARCHITECTUAL_BOOK_RESIDENTIAL_SELECTED";
      
      public static const ARCHITECTUAL_BOOK_PRODUCTION_SELECTED:String = "ARCHITECTUAL_BOOK_PRODUCTION_SELECTED";
      
      public static const ARCHITECTUAL_BOOK_INFRASTRUCTURE_SELECTED:String = "ARCHITECTUAL_BOOK_INFRASTRUCTURE_SELECTED";
      
      public static const ARCHITECTUAL_BOOK_DECORATION_SELECTED:String = "ARCHITECTUAL_BOOK_DECORATION_SELECTED";
      
      public static const ARCHITECTUAL_BOOK_SHOP_SELECTED:String = "ARCHITECTUAL_BOOK_SHOP_SELECTED";
      
      public static const ARCHITECTUAL_BOOK_POWERPLANT_SELECTED:String = "ARCHITECTUAL_BOOK_POWERPLANT_SELECTED";
      
      public static const ARCHITECTURAL_CATEGORY_GROUNDS_SELECTED:String = "ARCHITECTURAL_CATEGORY_GROUNDS_SELECTED";
      
      public static const ARCHITECTURAL_DETAIL_RESIDENTIAL_SELECTED:String = "ARCHITECTURAL_DETAIL_RESIDENTIAL_SELECTED";
      
      public static const ARCHITECTURAL_DETAIL_GROUND_SELECTED:String = "ARCHITECTURAL_DETAIL_GROUND_SELECTED";
      
      public static const APPMODE_BUILD_DEINITIALZE:String = "APPMODE_BUILD_DEINITIALZE";
      
      public static const MINILAYER_CONSTRUCTION_OPENED:String = "MINILAYER_CONSTRUCTION_OPENED";
      
      public static const MINILAYER_CONSTRUCTION_CLOSED:String = "MINILAYER_CONSTRUCTION_CLOSED";
      
      public static const PRODUCTIONLAYER_CLOSED:String = "PRODUCTIONLAYER_CLOSED";
      
      public static const RESIDENTIALLAYED_CLOSED:String = "RESIDENTIALLAYED_CLOSED";
      
      public static const RESIDENTIALLAYED_OPENED:String = "RESIDENTIALLAYED_OPENED";
      
      public static const PRODUCTIONLAYER_OPENED:String = "PRODUCTIONLAYER_OPENED";
      
      public static const UPGRADEREADY_RESIDENTIAL_LAYEROPENED:String = "UPGRADEREADY_RESIDENTIAL_LAYEROPENED";
      
      public static const MINILAYER_BUYEXPANSION_OPENED:String = "MINILAYER_BUYEXPANSION_OPENED";
      
      public static const MINILAYER_BUYEXPANSION_CLOSED:String = "MINILAYER_BUYEXPANSION_CLOSED";
      
      public static const SHOPLAYER_CLOSED:String = "SHOPLAYER_CLOSED";
      
      public static const SHOPLAYER_OPENED:String = "SHOPLAYER_OPENED";
      
      public static const MAINMENUE_CURSORSUBMENUE_OPENED:String = "MAINMENUE_CURSORSUBMENUE_OPENED";
      
      public static const APPLICATIONMODES_MOVE_INIT:String = "APPLICATIONMODES_MOVE_INIT";
      
      public static const APPLICATIONMODES_MOVE_DEINIT:String = "APPLICATIONMODES_MOVE_DEINIT";
      
      public static const MAINMENUE_CURSORSUBMENUE_CLOSED:String = "MAINMENUE_CURSORSUBMENUE_CLOSED";
      
      public static const APPLICATIONMODES_DESTROY_DEINIT:String = "APPLICATIONMODES_DESTROY_DEINIT";
      
      public static const APPLICATIONMODES_DESTROY_INIT:String = "APPLICATIONMODES_DESTROY_INIT";
      
      public static const RESIDENT_SELECTIONLAYER_CLOSED:String = "RESIDENT_SELECTIONLAYER_CLOSED";
      
      public static const RESIDENT_SELECTED_FOR_MOVEIN:String = "RESIDENT_SELECTED_FOR_MOVEIN";
      
      public static const CITYSQUARELAYER_DETAIL_CLOSED:String = "CITYSQUARELAYER_DETAIL_CLOSED";
      
      public static const CITYSQUARELAYER_DETAIL_OPENED:String = "CITYSQUARELAYER_DETAIL_OPENED";
      
      public static const ARCHITECTUAL_BOOK_FIREDEPARTMENT_SELECTED:String = "ARCHITECTUAL_BOOK_FIREDEPARTMENT_SELECTED";
      
      public static const ARCHITECTUAL_BOOK_HYDRANT_SELECTED:String = "ARCHITECTUAL_BOOK_HYDRANT_SELECTED";
      
      public static const EMERGENCY_BOOK_OPENED:String = "EMERGENCY_BOOK_OPENED";
      
      public static const EMERGENCY_BOOK_PROFESSIONAL_SLOT_CLICKED:String = "EMERGENCY_BOOK_PROFESSIONAL_SLOT_CLICKED";
      
      public static const EMERGENCY_BOOK_PROFESSIONAL_SELECTED:String = "EMERGENCY_BOOK_PROFESSIONAL_SELECTED";
      
      public static const BOOSTERPACK_STORE_OPENED:String = "BOOSTERPACK_STORE_OPENED";
      
      public static const BUILDING_REPAIR_LAYER_OPENED:String = "BUILDING_REPAIR_LAYER_OPENED";
      
      public static const FIRE_DEPARTMENT_LAYER_OPENED:String = "FIRE_DEPARTMENT_LAYER_OPENED";
      
      public static const FIRE_DEPARTMENT_DETAIL_LAYER_OPENED:String = "FIRE_DEPARTMENT_DETAIL_LAYER_OPENED";
      
      public static const ACADEMY_LAYER_OPENED:String = "ACADEMY_LAYER_OPENED";
      
      public static const EMERGENCY_BOOK_CLOSED:String = "EMERGENCY_BOOK_CLOSED";
      
      public static const BOOSTERPACK_STORE_CLOSED:String = "BOOSTERPACK_STORE_CLOSED";
      
      public static const BUILDING_REPAIR_LAYER_CLOSED:String = "BUILDING_REPAIR_LAYER_CLOSED";
      
      public static const ACADEMY_LAYER_CLOSED:String = "ACADEMY_LAYER_CLOSED";
      
      public static const FIRE_DEPARTMENT_LAYER_CLOSED:String = "FIRE_DEPARTMENT_LAYER_CLOSED";
      
      public static const ARCHITECTUAL_BOOK_SPECIAL_SELECTED:String = "ARCHITECTUAL_BOOK_SPECIAL_SELECTED";
      
      public static const OPTIONS_MENU_EXPANDED:String = "OPTIONS_MENU_EXPANDED";
      
      public static const OPTIONS_MENU_COLLAPSED:String = "OPTIONS_MENU_COLLAPSED";
      
      public static const IMPROVEMENT_SHOP_OPENED:String = "IMPROVEMENT_SHOP_OPENED";
      
      public static const IMPROVEMENT_SHOP_CLOSED:String = "IMPROVEMENT_SHOP_CLOSED";
      
      public static const RESIDENTIALLAYER_IMPROVEMENT_CLOSED:String = "RESIDENTIALLAYER_IMPROVEMENT_CLOSED";
      
      public static const RESIDENTIALLAYER_IMPROVEMENT_OPENED:String = "RESIDENTIALLAYER_IMPROVEMENT_OPENED";
      
      public static const APPLICATIONMODES_IMROVEMENT_DEINIT:String = "APPLICATIONMODES_IMROVEMENT_DEINIT";
      
      public static const APPLICATIONMODES_IMROVEMENT_INIT:String = "APPLICATIONMODES_IMROVEMENT_INIT";
      
      public static const RENTCOLLECTOR_MINILAYER_OPENED:String = "RENTCOLLECTOR_MINILAYER_OPENED";
      
      public static const RENTCOLLECTOR_MINILAYER_CLOSED:String = "RENTCOLLECTOR_MINILAYER_CLOSED";
      
      public static const CITY_TREASURY_OPENED:String = "CITY_TREASURY_OPENED";
      
      public static const CITY_TREASURY_CLOSED:String = "CITY_TREASURY_CLOSED";
      
      public static const CITYSQUARELAYER_SELECTION_OPENED:String = "CITYSQUARELAYER_SELECTION_OPENED";
      
      public static const CITYSQUARELAYER_SELECTION_CLOSED:String = "CITYSQUARELAYER_SELECTION_CLOSED";
      
      public static const PLAYFIELDSWITCH_MINILAYER_OPENED:String = "PLAYFIELDSWITCH_MINILAYER_OPENED";
      
      public static const PLAYFIELDSWITCH_MINILAYER_CLOSED:String = "PLAYFIELDSWITCH_MINILAYER_CLOSED";
      
      public static const FEATURED_EVENT_LAYER_CLOSED:String = "FEATURED_EVENT_LAYER_CLOSED";
      
      public static const FEATURED_EVENT_LAYER_OPENED:String = "FEATURED_EVENT_LAYER_OPENED";
      
      public static const ARCHITECTURAL_BOOK_CINEMA_SELECTED:String = "ARCHITECTURAL_BOOK_CINEMA_SELECTED";
      
      public static const INGAME_STORE_OPENED:String = "INGAME_STORE_OPENED";
      
      public static const INGAME_STORE_CLOSED:String = "INGAME_STORE_CLOSED";
      
      public static const CITY_WHEEL_LAYER_OPEN:String = "CITY_WHEEL_LAYER_OPEN";
      
      public static const CITY_WHEEL_LAYER_CLOSED:String = "CITY_WHEEL_LAYER_CLOSED";
      
      public function VirtualTaskNotificationInterest()
      {
         super();
      }
   }
}

