package net.bigpoint.cityrama.controller.applicationStartup.prepCommands.controller
{
   import net.bigpoint.cityrama.constants.ServerNotificationConstants;
   import net.bigpoint.cityrama.controller.newsscreen.ServerMessagePlayerNewsscreenUpdateCommand;
   import net.bigpoint.cityrama.controller.server.ServerConnectionClosed;
   import net.bigpoint.cityrama.controller.server.ServerMarketOfferSoldCommand;
   import net.bigpoint.cityrama.controller.server.ServerMessagePlayerLevelUpSuccessCommand;
   import net.bigpoint.cityrama.controller.server.ServerMessagePlayfieldBuildingConstructionPhaseupdateCommand;
   import net.bigpoint.cityrama.controller.server.ServerMessagePlayfieldBuildingHarvestphaseUpdateCommand;
   import net.bigpoint.cityrama.controller.server.ServerMessagePlayfieldDecorationDeleteFailed;
   import net.bigpoint.cityrama.controller.server.ServerMessageResourcesCommand;
   import net.bigpoint.cityrama.controller.server.ServerMessageTimeUpdateCommand;
   import net.bigpoint.cityrama.controller.server.ServerPMSNewMessageCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessageConnectionIdleClose;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessageCreateBuildingFailedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessageIllegalParamFailCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePaymentPackBookedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePaymentPackUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayerFeatureUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBoulderCreatedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBoulderDeletedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBoulderDestructionPhaseUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBoulderPhaseStartedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBuildingConstructionFinishedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBuildingNewCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBuildingPhaseNewCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBuildingRandomDropCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBuildingResidentSwapSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldBuildingUpgradePhaseUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldCreateDecorationSuccess;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldCreateGroundFailed;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldCreateGroundSuccess;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldDecorationCreateFailed;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldDecorationDeleteSuccess;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldDecorationMoveFailed;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldDecorationMoveSuccess;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldDeleteGroundFailed;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldDestroyGroundSuccess;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldItemBoostPhaseUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldMoveGroundFailed;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldMoveGroundSuccess;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldNeedConsumedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldProductionCancelFailedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldProductionCancelSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldProductionFailedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldProductionHarvestFailedCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldProductionHarvestSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldProductionPhaseupdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldStackNeedSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessagePlayfieldUpdateGroundSuccess;
   import net.bigpoint.cityrama.controller.server.messages.ServerMessageSwitchFeatureActionCommand;
   import net.bigpoint.cityrama.controller.server.messages.boosterpack.server.ServerMessageBoosterRewardSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.cinema.server.ServerMessageCinemaUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.cityTreasury.ServerMessagePlayerPaymentUpsellUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.cityWheel.server.ServerMessageCityWheelUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.common.ServerMessageRentCollectorSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.education.ServerMessageEducationExtendFailCommand;
   import net.bigpoint.cityrama.controller.server.messages.education.ServerMessageEducationExtendSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.education.ServerMessageEducationFinishedCommand;
   import net.bigpoint.cityrama.controller.server.messages.education.ServerMessageEducationStackCreatedCommand;
   import net.bigpoint.cityrama.controller.server.messages.education.ServerMessageProfessionalAssignedSuccess;
   import net.bigpoint.cityrama.controller.server.messages.education.ServerMessageProfessionalAttributeChangeFailCommand;
   import net.bigpoint.cityrama.controller.server.messages.education.ServerMessageProfessionalAttributeChangeSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.education.ServerMessageStartEducationFailCommand;
   import net.bigpoint.cityrama.controller.server.messages.education.ServerMessageStartEducationSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.education.ServernMessageProfessionalSpecializationChangedCommand;
   import net.bigpoint.cityrama.controller.server.messages.emergency.server.ServerMessageEmergencyFinishCommand;
   import net.bigpoint.cityrama.controller.server.messages.emergency.server.ServerMessageEmergencyUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.friend.ServerMessageFriendsUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.friend.ServerMessageSlayerInviteFriendFailedCommand;
   import net.bigpoint.cityrama.controller.server.messages.friend.ServerMessageSlayerInviteFriendSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.friend.ServerMessageSlayerRequestFriendFailedCommand;
   import net.bigpoint.cityrama.controller.server.messages.improvements.server.ServerMessageImprovementBoosterRewardSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.improvements.server.ServerMessagePlayfieldItemImprovementDeletedCommand;
   import net.bigpoint.cityrama.controller.server.messages.improvements.server.ServerMessagePlayfieldItemImprovementEquippedCommand;
   import net.bigpoint.cityrama.controller.server.messages.improvements.server.ServerMessagePlayfieldItemImprovementUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.inventory.server.ServerMessageExpandInventoryBagSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.inventory.server.ServerMessageInventoryUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.mastery.server.ServerMessageMasteryBonusUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.mastery.server.ServerMessageMasteryChallengeUpdateCommand;
   import net.bigpoint.cityrama.controller.server.messages.move.ServerMessagePlayfieldBuildingMoveFailedCommand;
   import net.bigpoint.cityrama.controller.server.messages.move.ServerMessagePlayfieldBuildingMoveSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.move.ServerMessagePlayfieldItemActiveStateChangedCommand;
   import net.bigpoint.cityrama.controller.server.messages.playfieldExpand.ServerMessagePlayfieldExpandFailed;
   import net.bigpoint.cityrama.controller.server.messages.playfieldExpand.ServerMessagePlayfieldExpandSuccess;
   import net.bigpoint.cityrama.controller.server.messages.playfieldExpand.ServerMessagePlayfieldSwitchSuccessCommand;
   import net.bigpoint.cityrama.controller.server.messages.professionals.server.ServerMessageProfessionalChangeSuccess;
   import net.bigpoint.cityrama.controller.server.messages.professionals.server.ServerMessageProfessionalCreateSuccess;
   import net.bigpoint.cityrama.controller.server.messages.professionals.server.ServerMessageProfessionalDismissSuccess;
   import org.puremvc.as3.interfaces.INotification;
   import org.puremvc.as3.patterns.command.SimpleCommand;
   
   public class ControllerPrepCommandServerClientCommunication extends SimpleCommand
   {
      
      public function ControllerPrepCommandServerClientCommunication()
      {
         super();
      }
      
      override public function execute(param1:INotification) : void
      {
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_TIMESTAMP_RESPONSE,ServerMessageTimeUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PMS_PUSH_NEW_MESSAGE,ServerPMSNewMessageCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_MARKET_PUSH_NOTIFICATION_MESSAGE,ServerMarketOfferSoldCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_CONNECTION_IDLE_CLOSE,ServerMessageConnectionIdleClose);
         facade.registerCommand(ServerNotificationConstants.SERVER_ILLEGAL_PARAM_FAIL,ServerMessageIllegalParamFailCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_CONNECTION_CLOSED,ServerConnectionClosed);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_HARVESTHELPER_RESIDENTIAL_SUCCESS_SPOOL,ServerMessageRentCollectorSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_ITEM_BOOSTPHASE_UPDATE,ServerMessagePlayfieldItemBoostPhaseUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_NEW,ServerMessagePlayfieldBuildingNewCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_CREATE_FAILED,ServerMessageCreateBuildingFailedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_CONSTRUCTIONPHASE_UPDATE,ServerMessagePlayfieldBuildingConstructionPhaseupdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_HARVESTPHASE_UPDATE,ServerMessagePlayfieldBuildingHarvestphaseUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_UPGRADEPHASE_UPDATE,ServerMessagePlayfieldBuildingUpgradePhaseUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_CONSTRUCTION_FINISHED,ServerMessagePlayfieldBuildingConstructionFinishedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_PHASE_NEW,ServerMessagePlayfieldBuildingPhaseNewCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_RESIDENT_SWAP_SUCCESS,ServerMessagePlayfieldBuildingResidentSwapSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_MOVE_FAILED,ServerMessagePlayfieldBuildingMoveFailedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_MOVE_SUCCESS,ServerMessagePlayfieldBuildingMoveSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELDITEM_ACTIVE_STATE_CHANGED,ServerMessagePlayfieldItemActiveStateChangedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_CREATE_GROUND_SUCCESS,ServerMessagePlayfieldCreateGroundSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_UPDATE_GROUND_SUCCESS,ServerMessagePlayfieldUpdateGroundSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_CREATE_GROUND_FAILED,ServerMessagePlayfieldCreateGroundFailed);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_DESTROY_GROUND_SUCCESS,ServerMessagePlayfieldDestroyGroundSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_DESTROY_GROUND_FAILED,ServerMessagePlayfieldDeleteGroundFailed);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_MOVE_GROUND_SUCCESS,ServerMessagePlayfieldMoveGroundSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_MOVE_GROUND_FAILED,ServerMessagePlayfieldMoveGroundFailed);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BOULDER_CREATED,ServerMessagePlayfieldBoulderCreatedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BOULDER_PHASE_STARTED,ServerMessagePlayfieldBoulderPhaseStartedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BOULDER_DESTRUCTIONPHASE_UPDATE,ServerMessagePlayfieldBoulderDestructionPhaseUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BOULDER_DELETED,ServerMessagePlayfieldBoulderDeletedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_SWITCH_SUCCESS,ServerMessagePlayfieldSwitchSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_EXPAND_FAILED,ServerMessagePlayfieldExpandFailed);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_EXPAND_SUCCESS,ServerMessagePlayfieldExpandSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_DELETE_DECORATION_SUCCESS,ServerMessagePlayfieldDecorationDeleteSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_CREATE_DECORATION_SUCCESS,ServerMessagePlayfieldCreateDecorationSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_CREATE_DECORATION_FAILED,ServerMessagePlayfieldDecorationCreateFailed);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_MOVE_DECORATION_FAILED,ServerMessagePlayfieldDecorationMoveFailed);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_MOVE_DECORATION_SUCCESS,ServerMessagePlayfieldDecorationMoveSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_DELETE_DECORATION_FAILED,ServerMessagePlayfieldDecorationDeleteFailed);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_RESOURCES,ServerMessageResourcesCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYER_LEVEL_UP_SUCCESS,ServerMessagePlayerLevelUpSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYER_BOOKED_PAYMENTPACK,ServerMessagePaymentPackBookedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYER_PAYMENTPACK_UPDATE,ServerMessagePaymentPackUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_PRODUCTION_PHASEUPDATE,ServerMessagePlayfieldProductionPhaseupdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_PRODUCTION_FAILED,ServerMessagePlayfieldProductionFailedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_PRODUCTION_HARVEST_SUCCESS,ServerMessagePlayfieldProductionHarvestSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_PRODUCTION_HARVEST_FAILED,ServerMessagePlayfieldProductionHarvestFailedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_PRODUCTION_CANCEL_SUCCESS,ServerMessagePlayfieldProductionCancelSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_PRODUCTION_CANCEL_FAILED,ServerMessagePlayfieldProductionCancelFailedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_STACK_NEED_SUCCESS,ServerMessagePlayfieldStackNeedSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_NEED_CONSUMED,ServerMessagePlayfieldNeedConsumedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_FRIENDS_UPDATE,ServerMessageFriendsUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_SLAYER_INVITE_FRIEND_SUCCESS,ServerMessageSlayerInviteFriendSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_SLAYER_INVITE_FRIEND_FAILED,ServerMessageSlayerInviteFriendFailedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_SLAYER_REQUEST_FRIENDLIST_FAILED,ServerMessageSlayerRequestFriendFailedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_SWITCH_FEATURE_ACTIVATION,ServerMessageSwitchFeatureActionCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_BUILDING_RANDOM_DROP,ServerMessagePlayfieldBuildingRandomDropCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_EMERGENCY_UPDATE,ServerMessageEmergencyUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELD_EMERGENCY_FINISH,ServerMessageEmergencyFinishCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PROFESSIONAL_CREATE_SUCCESS,ServerMessageProfessionalCreateSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PROFESSIONAL_DISMISS_SUCCESS,ServerMessageProfessionalDismissSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PROFESSIONAL_CHANGE_SUCCESS,ServerMessageProfessionalChangeSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_BOOSTER_REWARD_SUCCESS,ServerMessageBoosterRewardSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_EDUCATION_CREATED,ServerMessageEducationStackCreatedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_EDUCATION_EXTEND_SUCCESS,ServerMessageEducationExtendSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_EDUCATION_EXTEND_FAIL,ServerMessageEducationExtendFailCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_START_EDUCATION_SUCCESS,ServerMessageStartEducationSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_START_EDUCATION_FAIL,ServerMessageStartEducationFailCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PROFESSIONAL_ATTRIBUTE_CHANGE_SUCCESS,ServerMessageProfessionalAttributeChangeSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PROFESSIONAL_ATTRIBUTE_CHANGE_FAIL,ServerMessageProfessionalAttributeChangeFailCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_EDUCATION_FINISHED,ServerMessageEducationFinishedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PROFESSIONAL_ASSIGNED_SUCCESS,ServerMessageProfessionalAssignedSuccess);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PROFESSIONAL_SPECIALIZATION_CHANGE,ServernMessageProfessionalSpecializationChangedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_INVENTORY_UPDATE,ServerMessageInventoryUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_EXPAND_INVENTORY_BAG_SUCCESS,ServerMessageExpandInventoryBagSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYER_NEWSSCREEN_UPDATE,ServerMessagePlayerNewsscreenUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_IMPROVEMENT_BOOSTER_REWARD_SUCCESS,ServerMessageImprovementBoosterRewardSuccessCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELDITEM_IMPROVEMENT_DELETED,ServerMessagePlayfieldItemImprovementDeletedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELDITEM_IMPROVEMENT_EQUIPPED,ServerMessagePlayfieldItemImprovementEquippedCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYFIELDITEM_IMPROVEMENT_UPDATED,ServerMessagePlayfieldItemImprovementUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYER_FEATURE_UPDATE,ServerMessagePlayerFeatureUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_CITY_WHEEL_UPDATE,ServerMessageCityWheelUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_MASTERY_CHALLENGE_UPDATE,ServerMessageMasteryChallengeUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_MASTERY_BONUS_UPDATE,ServerMessageMasteryBonusUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_CINEMA_UPDATE,ServerMessageCinemaUpdateCommand);
         facade.registerCommand(ServerNotificationConstants.SERVER_MESSAGE_PLAYER_PAYMENT_UPSELL_UPDATE,ServerMessagePlayerPaymentUpsellUpdateCommand);
      }
   }
}

