package net.bigpoint.cityrama.controller.applicationStartup.prepCommands.controller
{
   import net.bigpoint.cityrama.constants.ApplicationNotificationConstants;
   import net.bigpoint.cityrama.constants.MiniLayerConstants;
   import net.bigpoint.cityrama.controller.architectBook.OpenItemInArchitectBookCommand;
   import net.bigpoint.cityrama.controller.assistants.OpenRentCollectorActivatedLayerCommand;
   import net.bigpoint.cityrama.controller.assistants.OpenRentCollectorLayerCommand;
   import net.bigpoint.cityrama.controller.bonusDay.OpenBonusDayActivatedLayerCommand;
   import net.bigpoint.cityrama.controller.boosterpackstore.BoosterpackBookAnimationCommand;
   import net.bigpoint.cityrama.controller.boosterpackstore.BoosterpackBookContentChangeCommand;
   import net.bigpoint.cityrama.controller.cinema.OpenCinemaLayerCommand;
   import net.bigpoint.cityrama.controller.cityTreasury.CityTreasuryTabChangedCommand;
   import net.bigpoint.cityrama.controller.cityTreasury.OpenCityTreasuryCommand;
   import net.bigpoint.cityrama.controller.cityTreasury.OpenCurrencyPurchaseCommand;
   import net.bigpoint.cityrama.controller.cityTreasury.OpenGoodPurchaseCommand;
   import net.bigpoint.cityrama.controller.citysquare.OpenCitySquareEventSelectionCommand;
   import net.bigpoint.cityrama.controller.citysquare.OpenCitySquareQuestByIdCommand;
   import net.bigpoint.cityrama.controller.citysquare.OpenCitysquareRequestNewEventCommand;
   import net.bigpoint.cityrama.controller.construction.OpenConstructionLayerCommand;
   import net.bigpoint.cityrama.controller.departmentBook.DeactivateEmergencyFeatureCommand;
   import net.bigpoint.cityrama.controller.departmentBook.DepartmentBookTabChangeCommand;
   import net.bigpoint.cityrama.controller.departmentBook.DepartmentOpenAcademyPopupCommand;
   import net.bigpoint.cityrama.controller.emergencyBook.OpenEmergencyInfoBookCommand;
   import net.bigpoint.cityrama.controller.emergencyBook.ShowCoverageInLayerCommand;
   import net.bigpoint.cityrama.controller.emergencyBook.ShowEmergencySlotCommand;
   import net.bigpoint.cityrama.controller.emergencyBook.ShowSpecialistDetailsInLayerCommand;
   import net.bigpoint.cityrama.controller.emergencyBook.StartEmergencyHandlingCommand;
   import net.bigpoint.cityrama.controller.error.OpenFatalErrorMinilayerCommand;
   import net.bigpoint.cityrama.controller.external.OpenMiniFlashUpgradePromotionCommand;
   import net.bigpoint.cityrama.controller.featureScreens.OpenBigFeatureOrCharacterScreenCommand;
   import net.bigpoint.cityrama.controller.featureScreens.OpenFeatureScreenCommand;
   import net.bigpoint.cityrama.controller.featuredEvent.FeaturedEventLayerChangeTabCommand;
   import net.bigpoint.cityrama.controller.featuredEvent.OpenFeaturedEventLayerCommand;
   import net.bigpoint.cityrama.controller.friend.FriendBookTabChangeCommand;
   import net.bigpoint.cityrama.controller.friend.OpenFriendBookCommand;
   import net.bigpoint.cityrama.controller.friend.OpenSlayerEMailCommand;
   import net.bigpoint.cityrama.controller.improvement.OpenResidentialImprovementPopupCommand;
   import net.bigpoint.cityrama.controller.improvement.improvementStore.ImprovementStoreAnimationCommand;
   import net.bigpoint.cityrama.controller.improvement.improvementStore.ImprovementStoreContentChangeCommand;
   import net.bigpoint.cityrama.controller.ingameStore.IngameStoreTabChangeCommand;
   import net.bigpoint.cityrama.controller.ingameStore.OpenIngameStorePopupCommand;
   import net.bigpoint.cityrama.controller.levelUp.OpenLevelUpPopUpCommand;
   import net.bigpoint.cityrama.controller.marketplace.OpenMarketPlaceByPHPCommand;
   import net.bigpoint.cityrama.controller.mastery.OpenMasteryTraitSelectionLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenCinemaRewardMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenCitysquareDepositMinilayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenCitysquareRewardPreviewMinilayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenCitysquareUpsellRewardMinilayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenClickInfoImprovementMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenConnectionLostMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenConstructionMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenDemolitionMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenEmergencyCleanupMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenEmergencyRehireProfessionalMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenEmergencyTimeUpMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenEquipImprovementMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenEvoucherFailureMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenExpansionMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenExpiredImprovementMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenFriendInviteMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenInfraUpgradeMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenLevelPreviewMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenLogoutMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenMarketPlaceInMaintanceMinilayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenMiniCityWheelRewardLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenMiniMasteryChallengeCompleteLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenMiniProfessionalLevelUp;
   import net.bigpoint.cityrama.controller.miniLayer.OpenMoveBlockedByEmergencyMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenMysteryConstructionMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenNoPermissionsLeftMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenPlacementMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenProductionCancelMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenProfessionalFireMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenProfessionalUnspentSkillpointsMinilayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenRemoveInventoryItemMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenReplaceExpiredImprovementMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenReplaceImprovementMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenTutorialRewardMiniLayerCommand;
   import net.bigpoint.cityrama.controller.miniLayer.OpenUpgradeMiniLayerCommand;
   import net.bigpoint.cityrama.controller.newsscreen.OpenNewsScreenCommand;
   import net.bigpoint.cityrama.controller.options.OptionsLayerOpenCommand;
   import net.bigpoint.cityrama.controller.payment.OpenPaymentByJSCommand;
   import net.bigpoint.cityrama.controller.payment.OpenPaymentWithItemByJSCommand;
   import net.bigpoint.cityrama.controller.payment.SendBonusCodeToPHPCommand;
   import net.bigpoint.cityrama.controller.popup.PopupCreateCommand;
   import net.bigpoint.cityrama.controller.popup.PopupExecuteCommand;
   import net.bigpoint.cityrama.controller.popup.PopupRemoveAllCommand;
   import net.bigpoint.cityrama.controller.popup.PopupRemoveCommand;
   import net.bigpoint.cityrama.controller.quest.OpenIntroductionLayerCommand;
   import net.bigpoint.cityrama.controller.quest.QuestTabChangeCommand;
   import net.bigpoint.cityrama.controller.residentSelection.OpenResidentSelectionCommand;
   import net.bigpoint.cityrama.controller.residentSelection.OpenResidentSwapCommand;
   import net.bigpoint.cityrama.controller.residentialBook.HarvestBuildingCommand;
   import net.bigpoint.cityrama.controller.residentialBook.OpenResidentialBookCommand;
   import net.bigpoint.cityrama.controller.residentialBook.ResidentialTabChangeCommand;
   import net.bigpoint.cityrama.controller.schoolBook.OpenSchoolBookCommand;
   import net.bigpoint.cityrama.controller.server.messages.ClientMessageConstructionInstantFinish;
   import net.bigpoint.cityrama.controller.server.messages.ClientMessageRequestUpgrade;
   import net.bigpoint.cityrama.controller.server.messages.ClientMessageUpgradeInstant;
   import net.bigpoint.cityrama.controller.server.messages.treasury.ClientMessageSwapCurrencyCommand;
   import net.bigpoint.cityrama.controller.storage.OpenStoragePopupCommand;
   import net.bigpoint.cityrama.controller.uiInfolayer.ShowAssistantInUiInfolayerCommand;
   import net.bigpoint.cityrama.controller.uiInfolayer.ShowGoodInUiInfolayerCommand;
   import net.bigpoint.cityrama.controller.uiInfolayer.ShowImprovementInUiInfolayerCommand;
   import net.bigpoint.cityrama.controller.uiInfolayer.ShowItemInUiInfolayerCommand;
   import net.bigpoint.cityrama.controller.uiInfolayer.ShowPlayfieldItemInUiInfolayerCommand;
   import net.bigpoint.cityrama.controller.uiInfolayer.ShowRessourceInUiInfolayerCommand;
   import net.bigpoint.cityrama.controller.upselling.OpenUpsellingNotificationLayerCommand;
   import net.bigpoint.cityrama.controller.upselling.OpenUpsellingOfferLayerCommand;
   import net.bigpoint.cityrama.controller.worldMap.OpenWorldMapCommand;
   import net.bigpoint.cityrama.controller.worldMap.OpenWorldMapOrLoadPlayfieldCommand;
   import net.bigpoint.cityrama.model.optionsMenu.OptionsMenuNavigationConstants;
   import org.puremvc.as3.interfaces.INotification;
   import org.puremvc.as3.patterns.command.SimpleCommand;
   
   public class ControllerPrepCommandPopups extends SimpleCommand
   {
      
      public function ControllerPrepCommandPopups()
      {
         super();
      }
      
      override public function execute(param1:INotification) : void
      {
         facade.registerCommand(OptionsMenuNavigationConstants.TOGGLE_SETTINGS,OptionsLayerOpenCommand);
         facade.registerCommand(ApplicationNotificationConstants.POPUP_CREATE,PopupCreateCommand);
         facade.registerCommand(ApplicationNotificationConstants.POPUP_EXECUTE,PopupExecuteCommand);
         facade.registerCommand(ApplicationNotificationConstants.POPUP_REMOVE,PopupRemoveCommand);
         facade.registerCommand(ApplicationNotificationConstants.POPUP_REMOVE_ALL,PopupRemoveAllCommand);
         facade.registerCommand(ApplicationNotificationConstants.UPGRADE_BILLBOARD_BUILDING,ClientMessageRequestUpgrade);
         facade.registerCommand(ApplicationNotificationConstants.INSTANT_FINISH_CONSTRUCTION_REQUEST,ClientMessageConstructionInstantFinish);
         facade.registerCommand(ApplicationNotificationConstants.INSTANT_UPGRADE_REQUEST,ClientMessageUpgradeInstant);
         facade.registerCommand(ApplicationNotificationConstants.SWAP_CURRENCY,ClientMessageSwapCurrencyCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_CONNECTIONLOST,OpenConnectionLostMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_TUTORIALREWARD,OpenTutorialRewardMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_INTRODUCTION,OpenIntroductionLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_CINEMA_REWARDS_LAYER,OpenCinemaRewardMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_EXPANSION,OpenExpansionMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_FRIENDINVITE,OpenFriendInviteMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_PLACEMENT,OpenPlacementMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_NO_PERMISSION,OpenNoPermissionsLeftMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_DEMOLITION,OpenDemolitionMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_PRODUCTION_CANCEL,OpenProductionCancelMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_CONSTRUCTION,OpenConstructionMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_MYSTERY_CONSTRUCTION,OpenMysteryConstructionMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_UPGRADE,OpenUpgradeMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_LOGOUT,OpenLogoutMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_LEVEL,OpenLevelPreviewMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_MARKET_MAINTANCE,OpenMarketPlaceInMaintanceMinilayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_FATAL_ERROR,OpenFatalErrorMinilayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_EMERGENCY_TIMEUP,OpenEmergencyTimeUpMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_EMERGENCY_CLEANUP,OpenEmergencyCleanupMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_EMERGENCY_REHIRE_PROFESSIONAL,OpenEmergencyRehireProfessionalMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_EVOUCHER_FAILURE,OpenEvoucherFailureMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_PROFESSIONAL_FIRE,OpenProfessionalFireMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_MOVE_BLOCKED,OpenMoveBlockedByEmergencyMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_REMOVE_INVENTORY_ITEM,OpenRemoveInventoryItemMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_INFRA_UPGRADE,OpenInfraUpgradeMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_PROFESSIONAL_LEVELUP,OpenMiniProfessionalLevelUp);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_FLASH_PLAYER_UPDATE_PROMOTION,OpenMiniFlashUpgradePromotionCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_IMPROVEMENT_EQUIP,OpenEquipImprovementMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_IMPROVEMENT_EXPIRED,OpenExpiredImprovementMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_IMPROVEMENT_INFO,OpenClickInfoImprovementMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_IMPROVEMENT_REPLACE,OpenReplaceImprovementMiniLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_IMPROVEMENT_REPLACE_EXPIRED,OpenReplaceExpiredImprovementMiniLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_FRIENDBOOK_POPUP,OpenFriendBookCommand);
         facade.registerCommand(ApplicationNotificationConstants.FRIENDBOOK_TAB_CHANGE,FriendBookTabChangeCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_RESIDENTIALBOOK,OpenResidentialBookCommand);
         facade.registerCommand(ApplicationNotificationConstants.RESIDENTIAL_TAB_CHANGED,ResidentialTabChangeCommand);
         facade.registerCommand(ApplicationNotificationConstants.HARVEST_BUILDING,HarvestBuildingCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_INGAME_STORE_POPUP,OpenIngameStorePopupCommand);
         facade.registerCommand(ApplicationNotificationConstants.INGAME_STORE_TAB_CHANGED,IngameStoreTabChangeCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_STORAGE_POPUP,OpenStoragePopupCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_SLAYER_EMAIL_DIALOG,OpenSlayerEMailCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_MARKETPLACE_PHP,OpenMarketPlaceByPHPCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_PAYMENT_BYJSCOMMAND,OpenPaymentByJSCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_PAYMENT_WITH_ITEM_BYJSCOMMAND,OpenPaymentWithItemByJSCommand);
         facade.registerCommand(ApplicationNotificationConstants.PAYMENT_SEND_BONUSCODE,SendBonusCodeToPHPCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_LEVEL_UP_SCREEN,OpenLevelUpPopUpCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_FEATURESCREEN,OpenFeatureScreenCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_RESIDENT_SELECTION,OpenResidentSelectionCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_RESIDENT_SWAP,OpenResidentSwapCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_CITYSQUARE_DEPOSIT,OpenCitysquareDepositMinilayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_CITYSQUARE_REWARD_PREVIEW,OpenCitysquareRewardPreviewMinilayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_CITYSQUARE_UPSELL_REWARD,OpenCitysquareUpsellRewardMinilayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_NEWSSCREEN_POPUP,OpenNewsScreenCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_EMERGENCY_INFOBOOK,OpenEmergencyInfoBookCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_COVERAGE_IN_EMERGENCY_LAYER,ShowCoverageInLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_SPECIALIST_DETAILS_IN_EMERGENCY_LAYER,ShowSpecialistDetailsInLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_SPECIALIST_SLOTS_IN_EMERGENCY_LAYER,ShowEmergencySlotCommand);
         facade.registerCommand(ApplicationNotificationConstants.START_EMERGENCY_HANDLING,StartEmergencyHandlingCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_SCHOOL_BOOK,OpenSchoolBookCommand);
         facade.registerCommand(ApplicationNotificationConstants.BOOSTERPACKBOOK_CONTENT_CHANGE,BoosterpackBookContentChangeCommand);
         facade.registerCommand(ApplicationNotificationConstants.BOOSTERPACKBOOK_ANIMATION,BoosterpackBookAnimationCommand);
         facade.registerCommand(ApplicationNotificationConstants.ACADEMY_OPEN,DepartmentOpenAcademyPopupCommand);
         facade.registerCommand(ApplicationNotificationConstants.DEPARTMENTBOOK_TAB_CHANGE,DepartmentBookTabChangeCommand);
         facade.registerCommand(ApplicationNotificationConstants.DEACTIVATE_EMERGENCY_FEATURE,DeactivateEmergencyFeatureCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_BIG_FEATURE_OR_CHARACTER_SCREEN,OpenBigFeatureOrCharacterScreenCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_PROFESSIONAL_UNSPENT_SKILLPOINTS_MINI_LAYER,OpenProfessionalUnspentSkillpointsMinilayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_HIP_POPUP,OpenResidentialImprovementPopupCommand);
         facade.registerCommand(ApplicationNotificationConstants.IMPROVEMENT_STORE_CONTENT_CHANGED,ImprovementStoreContentChangeCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_IMPROVEMENT_IN_UI_INFOLAYER,ShowImprovementInUiInfolayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_GOOD_IN_UI_INFOLAYER,ShowGoodInUiInfolayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_RESSOURCE_IN_UI_INFOLAYER,ShowRessourceInUiInfolayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_TREASAURY_ITEM_IN_UI_INFOLAYER,ShowTreasauryItemInUiInfolayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_BOOSTER_PACK_IN_UI_INFOLAYER,ShowBoosterPackInUiInfolayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_ITEM_IN_UI_INFOLAYER,ShowItemInUiInfolayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_PLAYFIELDITEM_IN_UI_INFOLAYER,ShowPlayfieldItemInUiInfolayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.SHOW_ASSISTANT_IN_UI_INFOLAYER,ShowAssistantInUiInfolayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.IMPROVEMENT_STORE_ANIMATION,ImprovementStoreAnimationCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_CITYSQUARE_QUEST_BY_ID,OpenCitySquareQuestByIdCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_CITYSQUARE_EVENT_SELECTION,OpenCitySquareEventSelectionCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_REQUEST_START_NEW_EVENT,OpenCitysquareRequestNewEventCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_FEATURED_LAYER,OpenFeaturedEventLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.FEATURED_LAYER_TAB_CHANGE,FeaturedEventLayerChangeTabCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_CITY_WHEEL_REWARDS_LAYER,OpenMiniCityWheelRewardLayerCommand);
         facade.registerCommand(MiniLayerConstants.OPEN_MINI_MASTERY_CHALLENGE_COMPLETE_LAYER,OpenMiniMasteryChallengeCompleteLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_MASTERY_TRAIT_SELECTION_LAYER,OpenMasteryTraitSelectionLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_CINEMA_LAYER,OpenCinemaLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_UPSELL_OFFER_LAYER,OpenUpsellingOfferLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_UPSELL_MINI_NOTIFICATION_LAYER,OpenUpsellingNotificationLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_BONUS_DAY_ACTIVATED_LAYER,OpenBonusDayActivatedLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.QUEST_TAB_CHANGED,QuestTabChangeCommand);
         facade.registerCommand(ApplicationNotificationConstants.CITY_TREASURY_TAB_CHANGED,CityTreasuryTabChangedCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_CITY_TREASURY,OpenCityTreasuryCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_GOOD_PURCHASE,OpenGoodPurchaseCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_CURRENCY_PURCHASE,OpenCurrencyPurchaseCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_ITEM_IN_ARCHITECT_BOOK,OpenItemInArchitectBookCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_CONSTRUCTION_LAYER,OpenConstructionLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_RENTCOLLECTOR_LAYER,OpenRentCollectorLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_RENTCOLLECTOR_ACTIVATED_LAYER,OpenRentCollectorActivatedLayerCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_WORLD_MAP,OpenWorldMapCommand);
         facade.registerCommand(ApplicationNotificationConstants.OPEN_WORLD_MAP_OR_LOAD_PLAYFIELD,OpenWorldMapOrLoadPlayfieldCommand);
      }
   }
}

