package net.bigpoint.cityrama.constants
{
   public class ServerNotificationConstants
   {
      
      public static const SERVER_MESSAGE_:String = "SERVER_MESSAGE_";
      
      public static const CLIENT_MESSAGE_:String = "CLIENT_MESSAGE_";
      
      public static const CLIENT_MESSAGE_TEST:String = "CLIENT_MESSAGE_TEST";
      
      public static const SERVER_NEW:String = "SERVER_NEW";
      
      public static const SERVER_NEW_MESSAGE:String = "SERVER_NEW_MESSAGE";
      
      public static const SERVER_CONNECTED:String = "SERVER_CONNECTED";
      
      public static const SERVER_CONNECTION_CLOSED:String = "SERVER_CONNECTION_CLOSED";
      
      public static const SERVER_CONNECTION_IDLE_CLOSE:String = SERVER_MESSAGE_ + "CONNECTION_IDLE_CLOSE";
      
      public static const SERVER_ILLEGAL_PARAM_FAIL:String = SERVER_MESSAGE_ + "ILLEGAL_PARAM_FAIL";
      
      public static const SERVER_PUSH_MAINTENANCE:String = "SERVER_PUSH_MAINTENANCE";
      
      public static const SERVER_PUSH_SHUTDOWN:String = "SERVER_PUSH_SHUTDOWN";
      
      public static const SERVER_PUSH_RECONNECT:String = "SERVER_PUSH_RECONNECT";
      
      public static const SERVER_MESSAGE_PROGRESS:String = "SERVER_MESSAGE_PROGRESS";
      
      public static const SERVER_MESSAGE_SPOOL:String = SERVER_MESSAGE_ + "SPOOL";
      
      public static const SERVER_MESSAGE_HARVESTHELPER_RESIDENTIAL_SUCCESS_SPOOL:String = SERVER_MESSAGE_ + "HARVESTHELPER_RESIDENTIAL_SUCCESS_SPOOL";
      
      public static const CLIENT_MESSAGE_LOGIN:String = CLIENT_MESSAGE_ + "LOGIN";
      
      public static const SERVER_MESSAGE_INITIAL_LOGIN_SUCCESS:String = SERVER_MESSAGE_ + "LOGIN_SUCCESS";
      
      public static const SERVER_MESSAGE_LOGIN_FAILED:String = SERVER_MESSAGE_ + "LOGIN_FAILED";
      
      public static const CLIENT_MESSAGE_LOGOUT:String = CLIENT_MESSAGE_ + "LOGOUT";
      
      public static const CLIENT_MESSAGE_TIMESTAMP_REQUEST:String = CLIENT_MESSAGE_ + "TIMESTAMP_REQUEST";
      
      public static const SERVER_MESSAGE_TIMESTAMP_RESPONSE:String = SERVER_MESSAGE_ + "TIMESTAMP_RESPONSE";
      
      public static const SERVER_MESSAGE_MIDSESSION_LOGIN_SUCCESS:String = SERVER_MESSAGE_ + "LOGIN_SUCCESS";
      
      public static const CLIENT_MESSAGE_SWITCH_PLAYFIELD:String = CLIENT_MESSAGE_ + "SWITCH_PLAYFIELD";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_LOAD:String = CLIENT_MESSAGE_ + "PLAYFIELD_LOAD";
      
      public static const SERVER_MESSAGE_PLAYFIELD_PLAYFIELDITEM_DELETE_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELDITEM_DELETE_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_PLAYFIELDITEM_DELETE_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELDITEM_DELETE_FAILED";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_BUILDING_DELETE:String = CLIENT_MESSAGE_ + "PLAYFIELD_BUILDING_DELETE";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_ITEM_CREATE:String = CLIENT_MESSAGE_ + "PLAYFIELD_ITEM_CREATE";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_DECORATION_CREATE:String = CLIENT_MESSAGE_ + "PLAYFIELD_DECORATION_CREATE";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_DECORATION_MOVE:String = CLIENT_MESSAGE_ + "PLAYFIELD_DECORATION_MOVE";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_DECORATION_DELETE:String = CLIENT_MESSAGE_ + "PLAYFIELD_DECORATION_DELETE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_CREATE_DECORATION_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_CREATE_DECORATION_FAILED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_CREATE_DECORATION_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_CREATE_DECORATION_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_MOVE_DECORATION_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_MOVE_DECORATION_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_MOVE_DECORATION_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_MOVE_DECORATION_FAILED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_DELETE_DECORATION_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_DELETE_DECORATION_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_DELETE_DECORATION_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_DELETE_DECORATION_FAILED";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_BUILDING_CREATE:String = CLIENT_MESSAGE_ + "PLAYFIELD_BUILDING_CREATE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_NEW:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_NEW";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_CREATE_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_CREATE_FAILED";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_BUILDING_CONSTRUCTIONPHASE_PROCESS:String = CLIENT_MESSAGE_ + "PLAYFIELD_BUILDING_PROCESSPHASE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_CONSTRUCTIONPHASE_UPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_CONSTRUCTIONPHASE_UPDATE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_HARVESTPHASE_UPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_HARVESTPHASE_UPDATE";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_CREATE_GROUND:String = CLIENT_MESSAGE_ + "PLAYFIELD_CREATE_GROUND";
      
      public static const SERVER_MESSAGE_PLAYFIELD_CREATE_GROUND_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_CREATE_GROUND_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_CREATE_GROUND_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_CREATE_GROUND_FAILED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_UPDATE_GROUND_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_UPDATE_GROUND_SUCCESS";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_DESTROY_GROUND:String = CLIENT_MESSAGE_ + "PLAYFIELD_DESTROY_GROUND";
      
      public static const SERVER_MESSAGE_PLAYFIELD_DESTROY_GROUND_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_DESTROY_GROUND_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_DESTROY_GROUND_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_DESTROY_GROUND_FAILED";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_MOVE_GROUND:String = CLIENT_MESSAGE_ + "PLAYFIELD_MOVE_GROUND";
      
      public static const SERVER_MESSAGE_PLAYFIELD_MOVE_GROUND_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_MOVE_GROUND_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_MOVE_GROUND_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_MOVE_GROUND_FAILED";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_BUILDING_INAUGURATE:String = CLIENT_MESSAGE_ + "PLAYFIELD_BUILDING_INAUGURATE ";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_BUILDING_SWAP_RESIDENT:String = CLIENT_MESSAGE_ + "PLAYFIELD_BUILDING_SWAP_RESIDENT";
      
      public static const SERVER_MESSAGE_PLAYFIELD_SWITCH_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_SWITCH_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BOULDER_CREATED:String = SERVER_MESSAGE_ + "PLAYFIELD_BOULDER_CREATED";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_BOULDER_PROCESSPHASE:String = CLIENT_MESSAGE_ + "PLAYFIELD_BOULDER_PROCESSPHASE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BOULDER_PHASE_STARTED:String = SERVER_MESSAGE_ + "PLAYFIELD_BOULDER_PHASE_STARTED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BOULDER_DESTRUCTIONPHASE_UPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_BOULDER_DESTRUCTIONPHASE_UPDATE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BOULDER_DELETED:String = SERVER_MESSAGE_ + "PLAYFIELD_BOULDER_DELETED";
      
      public static const CLIENT_MESSAGE_PLAYFIELDITEM_BUY_PERMISSION:String = CLIENT_MESSAGE_ + "PLAYFIELDITEM_BUY_PERMISSION";
      
      public static const SERVER_MESSAGE_PLAYFIELDITEM_BUY_PERMISSION_FAIL:String = SERVER_MESSAGE_ + "PLAYFIELDITEM_BUY_PERMISSION_FAIL";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_BUILDING_BOOSTPHASE:String = CLIENT_MESSAGE_ + "PLAYFIELD_BUILDING_BOOSTPHASE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_ITEM_BOOSTPHASE_UPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_ITEM_BOOSTPHASE_UPDATE";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_REQUEST_INSTANTFINISH:String = CLIENT_MESSAGE_ + "PLAYFIELD_REQUEST_INSTANTFINISH";
      
      public static const SERVER_MESSAGE_RESOURCES:String = SERVER_MESSAGE_ + "RESOURCES";
      
      public static const SERVER_MESSAGE_QUEST_NEW:String = SERVER_MESSAGE_ + "QUEST_NEW";
      
      public static const SERVER_MESSAGE_QUEST_TASK_UPDATE:String = SERVER_MESSAGE_ + "QUEST_TASK_UPDATE";
      
      public static const SERVER_MESSAGE_QUEST_UPDATE:String = SERVER_MESSAGE_ + "QUEST_UPDATE";
      
      public static const SERVER_MESSAGE_PLAYER_LEVEL_UP_SUCCESS:String = SERVER_MESSAGE_ + "PLAYER_LEVEL_UP_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_UPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_UPDATE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_EXPAND_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_EXPAND_FAILED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_EXPAND_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_EXPAND_SUCCESS";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_EXPAND:String = CLIENT_MESSAGE_ + "PLAYFIELD_EXPAND";
      
      public static const CLIENT_PAYMENT_SWAP_CURRENCY:String = CLIENT_MESSAGE_ + "PAYMENT_SWAP_CURRENCY";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_BUILDING_HARVESTPHASE_PROCESS:String = CLIENT_MESSAGE_ + "PLAYFIELD_BUILDING_HARVESTPHASE_PROCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_CONSTRUCTION_FINISHED:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_CONSTRUCTION_FINISHED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_UPGRADEPHASE_UPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_UPGRADEPHASE_UPDATE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_PHASE_NEW:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_PHASE_NEW";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_MOVE_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_MOVE_FAILED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_MOVE_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_MOVE_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELDITEM_ACTIVE_STATE_CHANGED:String = SERVER_MESSAGE_ + "PLAYFIELDITEM_ACTIVE_STATE_CHANGED";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_HARVEST_PRODUCTION:String = CLIENT_MESSAGE_ + "PLAYFIELD_HARVEST_PRODUCTION";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_CANCEL_PRODUCTION:String = CLIENT_MESSAGE_ + "PLAYFIELD_CANCEL_PRODUCTION";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_REQUEST_PRODUCTION:String = CLIENT_MESSAGE_ + "PLAYFIELD_REQUEST_PRODUCTION";
      
      public static const SERVER_MESSAGE_PLAYFIELD_PRODUCTION_PHASEUPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_PRODUCTION_PHASEUPDATE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_PRODUCTION_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_PRODUCTION_FAILED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_PRODUCTION_HARVEST_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_PRODUCTION_HARVEST_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_PRODUCTION_HARVEST_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_PRODUCTION_HARVEST_FAILED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_PRODUCTION_CANCEL_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_PRODUCTION_CANCEL_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_PRODUCTION_CANCEL_FAILED:String = SERVER_MESSAGE_ + "PLAYFIELD_PRODUCTION_CANCEL_FAILED";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_MOVE_BUILDING:String = CLIENT_MESSAGE_ + "PLAYFIELD_MOVE_BUILDING";
      
      public static const SERVER_MESSAGE_PLAYFIELD_STACK_NEED_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_STACK_NEED_SUCCESS";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_UNSTACK_NEED:String = CLIENT_MESSAGE_ + "PLAYFIELD_UNSTACK_NEED";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_STACK_NEED:String = CLIENT_MESSAGE_ + "PLAYFIELD_STACK_NEED";
      
      public static const SERVER_MESSAGE_PLAYFIELD_NEED_CONSUMED:String = SERVER_MESSAGE_ + "PLAYFIELD_NEED_CONSUMED";
      
      public static const CLIENT_MESSAGE_QUEST_TASK_PROCESS:String = CLIENT_MESSAGE_ + "QUEST_TASK_PROCESS";
      
      public static const CLIENT_MESSAGE_QUEST_ELEMENT_INSTANT_FINISH:String = CLIENT_MESSAGE_ + "QUEST_ELEMENT_INSTANT_FINISH";
      
      public static const SERVER_MESSAGE_SWITCH_FEATURE_ACTIVATION:String = SERVER_MESSAGE_ + "SWITCH_FEATURE_ACTIVATION";
      
      public static const CLIENT_PLAYER_INVITE_REQUESTFRIENDLIST:String = CLIENT_MESSAGE_ + "PLAYER_INVITE_REQUESTFRIENDLIST";
      
      public static const CLIENT_PLAYER_INVITE_FRIEND:String = CLIENT_MESSAGE_ + "PLAYER_INVITE_FRIEND";
      
      public static const CLIENT_PLAYER_ACCEPT_FRIEND:String = CLIENT_MESSAGE_ + "PLAYER_ACCEPT_FRIEND";
      
      public static const CLIENT_PLAYER_DECLINE_FRIEND:String = CLIENT_MESSAGE_ + "PLAYER_DECLINE_FRIEND";
      
      public static const CLIENT_PLAYER_CANCEL_FRIEND:String = CLIENT_MESSAGE_ + "PLAYER_CANCEL_FRIEND";
      
      public static const SERVER_MESSAGE_FRIENDS_UPDATE:String = SERVER_MESSAGE_ + "FRIENDS_UPDATE";
      
      public static const SERVER_MESSAGE_SLAYER_INVITE_FRIEND_SUCCESS:String = SERVER_MESSAGE_ + "SLAYER_INVITE_FRIEND_SUCCESS";
      
      public static const SERVER_MESSAGE_SLAYER_INVITE_FRIEND_FAILED:String = SERVER_MESSAGE_ + "SLAYER_INVITE_FRIEND_FAILED";
      
      public static const SERVER_MESSAGE_SLAYER_REQUEST_FRIENDLIST_FAILED:String = SERVER_MESSAGE_ + "SLAYER_REQUEST_FRIENDLIST_FAILED";
      
      public static const SERVER_MESSAGE_EVENT_UPDATE:String = SERVER_MESSAGE_ + "EVENT_UPDATE";
      
      public static const SERVER_MESSAGE_PMS_PUSH_NEW_MESSAGE:String = SERVER_MESSAGE_ + "PMS_PUSH_NEW_MESSAGE";
      
      public static const SERVER_MESSAGE_PLAYER_BOOKED_PAYMENTPACK:String = SERVER_MESSAGE_ + "PLAYER_BOOKED_PAYMENTPACK";
      
      public static const CLIENT_MESSAGE_QUEST_ELEMENT_CHANGE_STATE:String = CLIENT_MESSAGE_ + "QUEST_ELEMENT_CHANGE_STATE";
      
      public static const SERVER_MESSAGE_PLAYER_PAYMENTPACK_UPDATE:String = SERVER_MESSAGE_ + "PLAYER_PAYMENTPACK_UPDATE";
      
      public static const SERVER_MESSAGE_QUEST_CHALLENGE_UPDATE:String = SERVER_MESSAGE_ + "QUEST_CHALLENGE_UPDATE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_RESIDENT_SWAP_SUCCESS:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_RESIDENT_SWAP_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYFIELD_BUILDING_RANDOM_DROP:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_RANDOM_DROP";
      
      public static const SERVER_MESSAGE_MARKET_PUSH_NOTIFICATION_MESSAGE:String = SERVER_MESSAGE_ + "MARKET_PUSH_NOTIFICATION_MESSAGE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_EMERGENCY_UPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_EMERGENCY_UPDATE";
      
      public static const SERVER_MESSAGE_PLAYFIELD_EMERGENCY_FINISH:String = SERVER_MESSAGE_ + "PLAYFIELD_EMERGENCY_FINISH";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_PROCESS_EMERGENCY:String = CLIENT_MESSAGE_ + "PLAYFIELD_PROCESS_EMERGENCY";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_REPAIR_BUILDING:String = CLIENT_MESSAGE_ + "PLAYFIELD_REPAIR_BUILDING";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_COLLECT_EMERGENCY:String = CLIENT_MESSAGE_ + "PLAYFIELD_COLLECT_EMERGENCY";
      
      public static const CLIENT_MESSAGE_PROFESSIONAL_DISMISS:String = CLIENT_MESSAGE_ + "PROFESSIONAL_DISMISS";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_DISMISS_SUCCESS:String = SERVER_MESSAGE_ + "PROFESSIONAL_DISMISS_SUCCESS";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_DISMISS_FAILED:String = SERVER_MESSAGE_ + "PROFESSIONAL_DISMISS_FAILED";
      
      public static const CLIENT_MESSAGE_PROFESSIONAL_CREATE:String = CLIENT_MESSAGE_ + "PROFESSIONAL_CREATE";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_CREATE_SUCCESS:String = SERVER_MESSAGE_ + "PROFESSIONAL_CREATE_SUCCESS";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_CREATE_FAILED:String = SERVER_MESSAGE_ + "PROFESSIONAL_CREATE_FAILED";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_CHANGE_SUCCESS:String = SERVER_MESSAGE_ + "PROFESSIONAL_CHANGE_SUCCESS";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_CHANGE_FAIL:String = SERVER_MESSAGE_ + "PROFESSIONAL_CHANGE_FAIL";
      
      public static const CLIENT_MESSAGE_PROFESSIONAL_FIRE:String = CLIENT_MESSAGE_ + "PROFESSIONAL_FIRE";
      
      public static const CLIENT_MESSAGE_PROFESSIONAL_RENEW:String = CLIENT_MESSAGE_ + "PROFESSIONAL_RENEW";
      
      public static const CLIENT_MESSAGE_BOOSTERPACK_BUY:String = CLIENT_MESSAGE_ + "BOOSTERPACK_BUY";
      
      public static const SERVER_MESSAGE_BOOSTER_REWARD_SUCCESS:String = SERVER_MESSAGE_ + "BOOSTER_REWARD_SUCCESS";
      
      public static const SERVER_MESSAGE_EDUCATION_CREATED:String = SERVER_MESSAGE_ + "EDUCATION_CREATED";
      
      public static const CLIENT_MESSAGE_ADD_EDUCATION_STEP:String = CLIENT_MESSAGE_ + "ADD_EDUCATION_STEP";
      
      public static const CLIENT_MESSAGE_START_EDUCATION:String = CLIENT_MESSAGE_ + "START_EDUCATION";
      
      public static const CLIENT_MESSAGE_SPEND_SKILLPOINT:String = CLIENT_MESSAGE_ + "SPEND_SKILLPOINT";
      
      public static const CLIENT_MESSAGE_HIRE_PROFESSIONAL:String = CLIENT_MESSAGE_ + "HIRE_PROFESSIONAL";
      
      public static const SERVER_MESSAGE_EDUCATION_EXTEND_SUCCESS:String = SERVER_MESSAGE_ + "EDUCATION_EXTEND_SUCCESS";
      
      public static const SERVER_MESSAGE_EDUCATION_EXTEND_FAIL:String = SERVER_MESSAGE_ + "EDUCATION_EXTEND_FAIL";
      
      public static const SERVER_MESSAGE_START_EDUCATION_SUCCESS:String = SERVER_MESSAGE_ + "START_EDUCATION_SUCCESS";
      
      public static const SERVER_MESSAGE_START_EDUCATION_FAIL:String = SERVER_MESSAGE_ + "START_EDUCATION_FAIL";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_ATTRIBUTE_CHANGE_SUCCESS:String = SERVER_MESSAGE_ + "PROFESSIONAL_ATTRIBUTE_CHANGE_SUCCESS";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_ATTRIBUTE_CHANGE_FAIL:String = SERVER_MESSAGE_ + "PROFESSIONAL_ATTRIBUTE_CHANGE_FAIL";
      
      public static const SERVER_MESSAGE_EDUCATION_FINISHED:String = SERVER_MESSAGE_ + "EDUCATION_FINISHED";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_ASSIGNED_SUCCESS:String = SERVER_MESSAGE_ + "PROFESSIONAL_ASSIGNED_SUCCESS";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_SPECIALIZATION_CHANGE:String = SERVER_MESSAGE_ + "PROFESSIONAL_SPECIALIZATION_CHANGE";
      
      public static const CLIENT_MESSAGE_MOVE_INVENTORYITEM_TO_PLAYFIELD:String = CLIENT_MESSAGE_ + "MOVE_INVENTORYITEM_TO_PLAYFIELD ";
      
      public static const CLIENT_MESSAGE_MOVE_PLAYFIELDITEM_TO_INVENTORY:String = CLIENT_MESSAGE_ + "MOVE_PLAYFIELDITEM_TO_INVENTORY ";
      
      public static const CLIENT_MESSAGE_REMOVE_ITEM_FROM_INVENTORY:String = CLIENT_MESSAGE_ + "DELETE_INVENTORYITEM";
      
      public static const SERVER_MESSAGE_INVENTORY_UPDATE:String = SERVER_MESSAGE_ + "INVENTORY_UPDATE";
      
      public static const CLIENT_MESSAGE_EXPAND_INVENTORY_BAG:String = CLIENT_MESSAGE_ + "EXPAND_INVENTORY_BAG";
      
      public static const SERVER_MESSAGE_EXPAND_INVENTORY_BAG_SUCCESS:String = SERVER_MESSAGE_ + "EXPAND_INVENTORY_BAG_SUCCES";
      
      public static const CLIENT_MESSAGE_PLAYFIELD_USE_HARVESTHELPER_RESIDENTIAL:String = CLIENT_MESSAGE_ + "PLAYFIELD_USE_HARVESTHELPER_RESIDENTIAL";
      
      public static const SERVER_MESSAGE_PLAYER_CITY_UPDATE:String = SERVER_MESSAGE_ + "PLAYER_CITY_UPDATE";
      
      public static const CLIENT_MESSAGE_PROFESSIONAL_LEVEL_UP:String = CLIENT_MESSAGE_ + "PROFESSIONAL_LEVEL_UP";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_LEVEL_SUCCESS:String = SERVER_MESSAGE_ + "PROFESSIONAL_LEVEL_SUCCESS";
      
      public static const SERVER_MESSAGE_PROFESSIONAL_TRAIT_SUCCESS:String = SERVER_MESSAGE_ + "PROFESSIONAL_TRAIT_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYER_NEWSSCREEN_UPDATE:String = SERVER_MESSAGE_ + "PLAYER_NEWSSCREEN_UPDATE";
      
      public static const CLIENT_MESSAGE_PLAYER_REQUEST_NEWSSCREEN:String = CLIENT_MESSAGE_ + "PLAYER_REQUEST_NEWSSCREEN";
      
      public static const CLIENT_MESSAGE_EQUIP_PLAYFIELDITEM_IMPROVEMENT:String = CLIENT_MESSAGE_ + "EQUIP_PLAYFIELDITEM_IMPROVEMENT";
      
      public static const SERVER_MESSAGE_PLAYFIELDITEM_IMPROVEMENT_EQUIPPED:String = SERVER_MESSAGE_ + "PLAYFIELDITEM_IMPROVEMENT_EQUIPPED";
      
      public static const CLIENT_MESSAGE_PROLONG_PLAYFIELDITEM_IMPROVEMENT:String = CLIENT_MESSAGE_ + "PROLONG_PLAYFIELDITEM_IMPROVEMENT";
      
      public static const SERVER_MESSAGE_PLAYFIELDITEM_IMPROVEMENT_UPDATED:String = SERVER_MESSAGE_ + "PLAYFIELDITEM_IMPROVEMENT_UPDATED";
      
      public static const CLIENT_MESSAGE_DELETE_PLAYFIELDITEM_IMPROVEMENT:String = CLIENT_MESSAGE_ + "DELETE_PLAYFIELDITEM_IMPROVEMENT";
      
      public static const SERVER_MESSAGE_PLAYFIELDITEM_IMPROVEMENT_DELETED:String = SERVER_MESSAGE_ + "PLAYFIELDITEM_IMPROVEMENT_DELETED";
      
      public static const CLIENT_MESSAGE_IMPROVEMENT_BOOSTER_BUY:String = CLIENT_MESSAGE_ + "IMPROVEMENT_BOOSTER_BUY";
      
      public static const SERVER_MESSAGE_IMPROVEMENT_BOOSTER_REWARD_SUCCESS:String = SERVER_MESSAGE_ + "IMPROVEMENT_BOOSTER_REWARD_SUCCESS";
      
      public static const SERVER_MESSAGE_PLAYER_FEATURE_UPDATE:String = SERVER_MESSAGE_ + "PLAYER_FEATURE_UPDATE";
      
      public static const SERVER_MESSAGE_CITY_WHEEL_UPDATE:String = SERVER_MESSAGE_ + "CITY_WHEEL_UPDATE";
      
      public static const CLIENT_MESSAGE_CITY_WHEEL_SPIN:String = CLIENT_MESSAGE_ + "CITY_WHEEL_SPIN";
      
      public static const CLIENT_MESSAGE_CITY_WHEEL_COLLECT:String = CLIENT_MESSAGE_ + "CITY_WHEEL_COLLECT";
      
      public static const CLIENT_MESSAGE_MASTERY_BUILDING_PROCESS:String = CLIENT_MESSAGE_ + "MASTERY_BUILDING_PROCESS";
      
      public static const SERVER_MESSAGE_MASTERY_CHALLENGE_UPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_MASTERY_CHALLENGE_UPDATE";
      
      public static const SERVER_MESSAGE_MASTERY_BONUS_UPDATE:String = SERVER_MESSAGE_ + "PLAYFIELD_BUILDING_MASTERY_BONUS_UPDATE";
      
      public static const SERVER_MESSAGE_CINEMA_UPDATE:String = SERVER_MESSAGE_ + "CINEMA_UPDATE";
      
      public static const SERVER_MESSAGE_PLAYER_PAYMENT_UPSELL_UPDATE:String = SERVER_MESSAGE_ + "PLAYER_PAYMENT_UPSELL_UPDATE";
      
      public static const CLIENT_MESSAGE_UPDATE_CLIENT_UI_DATA:String = CLIENT_MESSAGE_ + "UPDATE_CLIENT_UI_DATA";
      
      public static const SERVER_MESSAGE_UPDATE_CLIENT_UI_DATA_SUCCESS:String = SERVER_MESSAGE_ + "UPDATE_CLIENT_UI_DATA_SUCCESS";
      
      public static const SET_USER_OPTIONS:String = "SET_USER_OPTIONS";
      
      public function ServerNotificationConstants()
      {
         super();
      }
   }
}

